### ISSUE TITLE
"Unable to determine GPU product family ID"

### ISSUE THREAD

**Issue by ScottVordem** [ZenitH-AT/nvidia-update#4] opened 2022-11-28 19:36 UTC
Happens every time I run the script, even as administrator. I just downloaded it and wanted to see how it works. I know for sure I already have the latest driver version but wanted to test your updater to see how well it works.

(Might be worth mentioning that I normally use [NVCleanInstall](https://www.techpowerup.com/nvcleanstall/), a closed source program that works similarly to yours).

```
Checking for script update...

        Current script version:         1.12
        Latest script version:          1.12

This is the latest script (version 1.12).

Detecting GPU and driver version information...

        Detected graphics card name:    GeForce RTX 3080
        Current driver version:         526.98

Unable to determine GPU product family ID. This should not happen.
Press any key to exit...
```

**Comment by asheingold** [comment] 2022-11-29 05:42
Duplicate of #2

**Comment by ZenitH-AT** [comment] 2022-11-29 17:01
Should be fixed now

**Closed as completed by ZenitH-AT** 2022-11-29 17:01 UTC
