### ISSUE TITLE
7-Zip doesn't extract files after installed by the script (without running the script again)

### ISSUE THREAD

**Issue by Sgt-Nukem** [ZenitH-AT/nvidia-update#7] opened 2022-12-04 09:36 UTC
Downloaded and ran `powershell -ExecutionPolicy Bypass -File nvidia-update.ps1`, got error I don't get:

![image](https://user-images.githubusercontent.com/4144388/205483688-d8742683-e3b7-4e89-81f6-330bc95ee47a.png)

**Comment by ZenitH-AT** [comment] 2022-12-04 09:57
That error is from 7-Zip extraction process, so it's probably something to with the extraction argument list string I'm using in the script. I'm likely incorrectly handling spaces in the user folder. It could also be caused by 7-Zip having just been installed.

Does the error occur if you try run the script again, now that 7-Zip is installed? If so, does the user folder you censored have a space in the name?

I'm planning to get a new release out soon so I'll fix this asap.

**Comment by ZenitH-AT** [comment] 2022-12-04 10:18
I just tested on a VM and was able to reproduce the error. It's not related to a space in the user folder name. I'm looking into the actual cause now.

**Comment by ZenitH-AT** [comment] 2022-12-04 10:26
> Does the error occur if you try run the script again, now that 7-Zip is installed?

I tested this on a VM and it works. Does it work for you, too? I'll need to figure out why 7-Zip can't be run after installation without running the script again.

I found that I wasn't setting the archiver path after 7-Zip installation, so added code to do that but it still sets it as null. ~~It seems PowerShell can't see registry changes made while the script is running.~~ I have an idea how to fix this and will update this comment when I do.

---

Fixed by https://github.com/ZenitH-AT/nvidia-update/commit/2b3e99ecb4762cb549424f26e6ad1029485552fc, there was more than one issue with the code causing this.

For now, just run the script again and it should work.

**Comment by ZenitH-AT** [comment] 2022-12-04 13:21
Fixed by https://github.com/ZenitH-AT/nvidia-update/commit/2b3e99ecb4762cb549424f26e6ad1029485552fc, which will be in the next release. Keep in mind this latest git version of the script won't detect GPU data until I update the [nvidia-data](https://github.com/ZenitH-AT/nvidia-data) repository.

For now, just run the existing release version of the script again and it should work.

**Closed as completed by ZenitH-AT** 2022-12-04 13:21 UTC
